### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arash-mazidi** [lindenb/jsandbox#4]
Hi,

I want to compile a .c program to webassembly. It generates .wasm files.
Then, I want to find the .c source that generated .wasm file. Actually, I want to find a relation between .wasm file and .c source file.
Does this tool can find this relation?

**Comment by lindenb** [comment]
no.

**Comment by arash-mazidi** [comment]
Thanks for your quick response.
Doesn't it consider a dependency between generated .wasm file and .c file?
I mean, .wasm file is depended on .c file. Cannot your tool find this dependency?

**Comment by lindenb** [comment]
> Cannot your tool find this dependency?

This project contains a bunch of one-shot tools. But I don't know about which tool you're talking. I think you're looking at the wrong project
